version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - symfony_network
    env_file:
      - .env  # Loads variables from .env into the container

  database:
    image: mysql:8.0
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge